version: '3.7'
services:
  bot:
    image: kindle-bot:latest
    container_name: kindle-bot
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data

